/*

 MIT License

 Copyright (c) 2023 Google LLC

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 */

import type { ILookmlModelExplore } from '@looker/sdk';
import type { TreeSelectProps } from '../TreeSelect';
import type { TreeModel } from './types';
import { Box, FieldToggleSwitch } from '@looker/components';
import { ExtendComponentsThemeProvider } from '@looker/components-providers';
import { Category } from '@looker/sdk';
import React, { useState } from 'react';
import { TreeSelect } from '../TreeSelect';
import { createExploreViewsTree } from './utils';

export const mockShortcutTree: TreeModel[] = [
  // doNotFilter
  {
    value: '',
    id: '.donotfilter',
    isOpen: true,
    label: 'Do Not Filter',
    isNotHighlightable: true,
    payload: {
      fieldOptions: {
        view_label: '',
        label_short: '',
      },
    },
  },

  // defaultField
  {
    value: 'Some Field',
    id: '.defaultField',
    isOpen: true,
    label: 'Some Field',
    isNotHighlightable: true,
    payload: {
      field: 'some_view.some_field',
      fieldOptions: {
        view_label: 'Some View',
        label_short: 'Some Field',
      },
    },
  },
];

export const mockTreeData: TreeModel[] = [
  {
    value: 'Root1',
    id: '.Root1_0',
    isOpen: false,
    children: [
      {
        value: 'some section',
        id: '.Root1_0.some section_0',
        isOpen: false,
        children: [
          {
            value: 'a leaf node',
            id: '.Root1_0.some section_0.a leaf node_0',
            isOpen: false,
            payload: {
              data: 'some data',
            },
          },
          {
            value: 'another leaf node',
            id: '.Root1_0.some section_0.another leaf node_1',
            isOpen: false,
            payload: {
              data: 'more data',
            },
          },
        ],
      },
      {
        value: 'anotha one',
        id: '.Root1_0.anotha one_1',
        isOpen: false,
        children: [
          {
            value: 'child of anotha one',
            id: '.Root1_0.anotha one_1.child of anotha one_0',
            isOpen: false,
            payload: {
              data: 'hello',
            },
          },
        ],
      },
    ],
  },
  {
    value: 'Root2',
    id: '.Root2_1',
    isOpen: false,
    children: [
      {
        value: 'some section2',
        id: '.Root2_1.some section2_0',
        isOpen: false,
        children: [
          {
            value: 'a leaf node2',
            id: '.Root2_1.some section2_0.a leaf node2_0',
            isOpen: false,
            payload: {
              data: 'some data',
            },
          },
          {
            value: 'another leaf node2',
            id: '.Root2_1.some section2_0.another leaf node2_1',
            isOpen: false,
            payload: {
              data: 'more data2',
            },
          },
        ],
      },
      {
        value: 'anotha one2',
        id: '.Root2_1.anotha one2_1',
        isOpen: false,
        children: [
          {
            value: 'child of anotha one',
            id: '.Root2_1.anotha one2_1.child of anotha one_0',
            isOpen: false,
            payload: {
              data: 'hello',
            },
          },
        ],
      },
    ],
  },
];

export const exploreData: ILookmlModelExplore = {
  id: 'thelook::orders',
  name: 'orders',
  description: null,
  title: 'Orders',
  fields: {
    dimensions: [
      {
        can_filter: true,
        category: Category.dimension,
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: 'Created Date',
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: false,
        label: 'Orders Created Date',
        label_from_parameter: null,
        label_short: 'Created Date',
        name: 'orders.created_date',
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'date_date',
        view: 'orders',
        view_label: 'Orders',
        dynamic: false,
        original_view: 'orders',
        dimension_group: 'orders.created',
        error: null,
        field_group_variant: 'Date',
        measure: false,
        parameter: false,
        primary_key: false,
        project_name: 'thelook',
        scope: 'orders',
        suggest_dimension: 'orders.created_date',
        suggest_explore: 'orders',
        suggestable: false,
        is_fiscal: false,
        is_timeframe: true,
        can_time_filter: false,
        lookml_link: '/projects/thelook/files/views%2Forders.view.lkml?line=11',
        permanent: null,
        source_file: 'views/orders.view.lkml',
        source_file_path: 'thelook/views/orders.view.lkml',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        can_filter: true,
        category: Category.dimension,
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: 'Created Date',
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: false,
        label: 'Orders Created Month',
        label_from_parameter: null,
        label_short: 'Created Month',
        name: 'orders.created_month',
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'date_month',
        view: 'orders',
        view_label: 'Orders',
        dynamic: false,
        original_view: 'orders',
        dimension_group: 'orders.created',
        error: null,
        field_group_variant: 'Month',
        measure: false,
        parameter: false,
        primary_key: false,
        project_name: 'thelook',
        scope: 'orders',
        suggest_dimension: 'orders.created_month',
        suggest_explore: 'orders',
        suggestable: false,
        is_fiscal: false,
        is_timeframe: true,
        can_time_filter: false,
        lookml_link: '/projects/thelook/files/views%2Forders.view.lkml?line=11',
        permanent: null,
        source_file: 'views/orders.view.lkml',
        source_file_path: 'thelook/views/orders.view.lkml',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        can_filter: true,
        category: Category.dimension,
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: 'Created Date',
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: false,
        label: 'Orders Created Quarter',
        label_from_parameter: null,
        label_short: 'Created Quarter',
        name: 'orders.created_quarter',
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'date_quarter',
        view: 'orders',
        view_label: 'Orders',
        dynamic: false,
        original_view: 'orders',
        dimension_group: 'orders.created',
        error: null,
        field_group_variant: 'Quarter',
        measure: false,
        parameter: false,
        primary_key: false,
        project_name: 'thelook',
        scope: 'orders',
        suggest_dimension: 'orders.created_quarter',
        suggest_explore: 'orders',
        suggestable: false,
        is_fiscal: false,
        is_timeframe: true,
        can_time_filter: false,
        lookml_link: '/projects/thelook/files/views%2Forders.view.lkml?line=11',
        permanent: null,
        source_file: 'views/orders.view.lkml',
        source_file_path: 'thelook/views/orders.view.lkml',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        can_filter: false,
        category: Category.dimension,
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: 'Created Date',
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: true,
        is_filter: false,
        is_numeric: false,
        label: 'Orders Created Raw',
        label_from_parameter: null,
        label_short: 'Created Raw',
        name: 'orders.created_raw',
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'date_raw',
        view: 'orders',
        view_label: 'Orders',
        dynamic: false,
        original_view: 'orders',
        dimension_group: 'orders.created',
        error: null,
        field_group_variant: 'Raw',
        measure: false,
        parameter: false,
        primary_key: false,
        project_name: 'thelook',
        scope: 'orders',
        suggest_dimension: 'orders.created_raw',
        suggest_explore: 'orders',
        suggestable: false,
        is_fiscal: false,
        is_timeframe: false,
        can_time_filter: false,
        lookml_link: '/projects/thelook/files/views%2Forders.view.lkml?line=11',
        permanent: null,
        source_file: 'views/orders.view.lkml',
        source_file_path: 'thelook/views/orders.view.lkml',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        can_filter: true,
        category: Category.dimension,
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: 'Created Date',
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: false,
        label: 'Orders Created Time',
        label_from_parameter: null,
        label_short: 'Created Time',
        name: 'orders.created_time',
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'date_time',
        view: 'orders',
        view_label: 'Orders',
        dynamic: false,
        original_view: 'orders',
        dimension_group: 'orders.created',
        error: null,
        field_group_variant: 'Time',
        measure: false,
        parameter: false,
        primary_key: false,
        project_name: 'thelook',
        scope: 'orders',
        suggest_dimension: 'orders.created_time',
        suggest_explore: 'orders',
        suggestable: false,
        is_fiscal: false,
        is_timeframe: true,
        can_time_filter: true,
        lookml_link: '/projects/thelook/files/views%2Forders.view.lkml?line=11',
        permanent: null,
        source_file: 'views/orders.view.lkml',
        source_file_path: 'thelook/views/orders.view.lkml',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        can_filter: true,
        category: Category.dimension,
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: 'Created Date',
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: false,
        label: 'Orders Created Week',
        label_from_parameter: null,
        label_short: 'Created Week',
        name: 'orders.created_week',
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'date_week',
        view: 'orders',
        view_label: 'Orders',
        dynamic: false,
        original_view: 'orders',
        dimension_group: 'orders.created',
        error: null,
        field_group_variant: 'Week',
        measure: false,
        parameter: false,
        primary_key: false,
        project_name: 'thelook',
        scope: 'orders',
        suggest_dimension: 'orders.created_week',
        suggest_explore: 'orders',
        suggestable: false,
        is_fiscal: false,
        is_timeframe: true,
        can_time_filter: false,
        lookml_link: '/projects/thelook/files/views%2Forders.view.lkml?line=11',
        permanent: null,
        source_file: 'views/orders.view.lkml',
        source_file_path: 'thelook/views/orders.view.lkml',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        can_filter: true,
        category: Category.dimension,
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: 'Created Date',
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: false,
        label: 'Orders Created Year',
        label_from_parameter: null,
        label_short: 'Created Year',
        name: 'orders.created_year',
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'date_year',
        view: 'orders',
        view_label: 'Orders',
        dynamic: false,
        original_view: 'orders',
        dimension_group: 'orders.created',
        error: null,
        field_group_variant: 'Year',
        measure: false,
        parameter: false,
        primary_key: false,
        project_name: 'thelook',
        scope: 'orders',
        suggest_dimension: 'orders.created_year',
        suggest_explore: 'orders',
        suggestable: false,
        is_fiscal: false,
        is_timeframe: true,
        can_time_filter: false,
        lookml_link: '/projects/thelook/files/views%2Forders.view.lkml?line=11',
        permanent: null,
        source_file: 'views/orders.view.lkml',
        source_file_path: 'thelook/views/orders.view.lkml',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        can_filter: true,
        category: Category.dimension,
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: null,
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: true,
        label: 'Orders ID',
        label_from_parameter: null,
        label_short: 'ID',
        name: 'orders.id',
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'number',
        view: 'orders',
        view_label: 'Orders',
        dynamic: false,
        original_view: 'orders',
        dimension_group: null,
        error: null,
        field_group_variant: 'ID',
        measure: false,
        parameter: false,
        primary_key: true,
        project_name: 'thelook',
        scope: 'orders',
        suggest_dimension: 'orders.id',
        suggest_explore: 'orders',
        suggestable: false,
        is_fiscal: false,
        is_timeframe: false,
        can_time_filter: false,
        lookml_link: '/projects/thelook/files/views%2Forders.view.lkml?line=5',
        permanent: null,
        source_file: 'views/orders.view.lkml',
        source_file_path: 'thelook/views/orders.view.lkml',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        can_filter: true,
        category: Category.dimension,
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: null,
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: false,
        label: 'Orders Status',
        label_from_parameter: null,
        label_short: 'Status',
        name: 'orders.status',
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'string',
        view: 'orders',
        view_label: 'Orders',
        dynamic: false,
        original_view: 'orders',
        dimension_group: null,
        error: null,
        field_group_variant: 'Status',
        measure: false,
        parameter: false,
        primary_key: false,
        project_name: 'thelook',
        scope: 'orders',
        suggest_dimension: 'orders.status',
        suggest_explore: 'orders',
        suggestable: true,
        is_fiscal: false,
        is_timeframe: false,
        can_time_filter: false,
        lookml_link: '/projects/thelook/files/views%2Forders.view.lkml?line=25',
        permanent: null,
        source_file: 'views/orders.view.lkml',
        source_file_path: 'thelook/views/orders.view.lkml',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        can_filter: true,
        category: Category.dimension,
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: null,
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: true,
        label: 'Orders User ID',
        label_from_parameter: null,
        label_short: 'User ID',
        name: 'orders.user_id',
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'number',
        view: 'orders',
        view_label: 'Orders',
        dynamic: false,
        original_view: 'orders',
        dimension_group: null,
        error: null,
        field_group_variant: 'User ID',
        measure: false,
        parameter: false,
        primary_key: false,
        project_name: 'thelook',
        scope: 'orders',
        suggest_dimension: 'orders.user_id',
        suggest_explore: 'orders',
        suggestable: false,
        is_fiscal: false,
        is_timeframe: false,
        can_time_filter: false,
        lookml_link: '/projects/thelook/files/views%2Forders.view.lkml?line=30',
        permanent: null,
        source_file: 'views/orders.view.lkml',
        source_file_path: 'thelook/views/orders.view.lkml',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        can_filter: true,
        category: Category.dimension,
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: null,
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: true,
        label: 'Users Age',
        label_from_parameter: null,
        label_short: 'Age',
        name: 'users.age',
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'number',
        view: 'users',
        view_label: 'Users',
        dynamic: false,
        original_view: 'users',
        dimension_group: null,
        error: null,
        field_group_variant: 'Age',
        measure: false,
        parameter: false,
        primary_key: false,
        project_name: 'thelook',
        scope: 'users',
        suggest_dimension: 'users.age',
        suggest_explore: 'orders',
        suggestable: false,
        is_fiscal: false,
        is_timeframe: false,
        can_time_filter: false,
        lookml_link: '/projects/thelook/files/views%2Fusers.view.lkml?line=11',
        permanent: null,
        source_file: 'views/users.view.lkml',
        source_file_path: 'thelook/views/users.view.lkml',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        can_filter: true,
        category: Category.dimension,
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: null,
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: false,
        label: 'Users City',
        label_from_parameter: null,
        label_short: 'City',
        name: 'users.city',
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'string',
        view: 'users',
        view_label: 'Users',
        dynamic: false,
        original_view: 'users',
        dimension_group: null,
        error: null,
        field_group_variant: 'City',
        measure: false,
        parameter: false,
        primary_key: false,
        project_name: 'thelook',
        scope: 'users',
        suggest_dimension: 'users.city',
        suggest_explore: 'orders',
        suggestable: true,
        is_fiscal: false,
        is_timeframe: false,
        can_time_filter: false,
        lookml_link: '/projects/thelook/files/views%2Fusers.view.lkml?line=16',
        permanent: null,
        source_file: 'views/users.view.lkml',
        source_file_path: 'thelook/views/users.view.lkml',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        can_filter: true,
        category: Category.dimension,
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: null,
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: false,
        label: 'Users Country',
        label_from_parameter: null,
        label_short: 'Country',
        map_layer: {
          url: '/data/world_noantarctica.topo-f95987c9c5.json',
          name: 'countries',
          feature_key: 'world',
          property_key: null,
          property_label_key: 'name',
          projection: 'kavrayskiy7',
          extents_json_url: null,
          max_zoom_level: null,
          min_zoom_level: null,
        },
        name: 'users.country',
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'string',
        view: 'users',
        view_label: 'Users',
        dynamic: false,
        original_view: 'users',
        dimension_group: null,
        error: null,
        field_group_variant: 'Country',
        measure: false,
        parameter: false,
        primary_key: false,
        project_name: 'thelook',
        scope: 'users',
        suggest_dimension: 'users.country',
        suggest_explore: 'orders',
        suggestable: true,
        is_fiscal: false,
        is_timeframe: false,
        can_time_filter: false,
        lookml_link: '/projects/thelook/files/views%2Fusers.view.lkml?line=21',
        permanent: null,
        source_file: 'views/users.view.lkml',
        source_file_path: 'thelook/views/users.view.lkml',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        can_filter: true,
        category: Category.dimension,
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: 'Created Date',
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: false,
        label: 'Users Created Date',
        label_from_parameter: null,
        label_short: 'Created Date',
        name: 'users.created_date',
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'date_date',
        view: 'users',
        view_label: 'Users',
        dynamic: false,
        original_view: 'users',
        dimension_group: 'users.created',
        error: null,
        field_group_variant: 'Date',
        measure: false,
        parameter: false,
        primary_key: false,
        project_name: 'thelook',
        scope: 'users',
        suggest_dimension: 'users.created_date',
        suggest_explore: 'orders',
        suggestable: false,
        is_fiscal: false,
        is_timeframe: true,
        can_time_filter: false,
        lookml_link: '/projects/thelook/files/views%2Fusers.view.lkml?line=27',
        permanent: null,
        source_file: 'views/users.view.lkml',
        source_file_path: 'thelook/views/users.view.lkml',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        can_filter: true,
        category: Category.dimension,
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: 'Created Date',
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: false,
        label: 'Users Created Month',
        label_from_parameter: null,
        label_short: 'Created Month',
        name: 'users.created_month',
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'date_month',
        view: 'users',
        view_label: 'Users',
        dynamic: false,
        original_view: 'users',
        dimension_group: 'users.created',
        error: null,
        field_group_variant: 'Month',
        measure: false,
        parameter: false,
        primary_key: false,
        project_name: 'thelook',
        scope: 'users',
        suggest_dimension: 'users.created_month',
        suggest_explore: 'orders',
        suggestable: false,
        is_fiscal: false,
        is_timeframe: true,
        can_time_filter: false,
        lookml_link: '/projects/thelook/files/views%2Fusers.view.lkml?line=27',
        permanent: null,
        source_file: 'views/users.view.lkml',
        source_file_path: 'thelook/views/users.view.lkml',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        can_filter: true,
        category: Category.dimension,
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: 'Created Date',
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: false,
        label: 'Users Created Quarter',
        label_from_parameter: null,
        label_short: 'Created Quarter',
        name: 'users.created_quarter',
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'date_quarter',
        view: 'users',
        view_label: 'Users',
        dynamic: false,
        original_view: 'users',
        dimension_group: 'users.created',
        error: null,
        field_group_variant: 'Quarter',
        measure: false,
        parameter: false,
        primary_key: false,
        project_name: 'thelook',
        scope: 'users',
        suggest_dimension: 'users.created_quarter',
        suggest_explore: 'orders',
        suggestable: false,
        is_fiscal: false,
        is_timeframe: true,
        can_time_filter: false,
        lookml_link: '/projects/thelook/files/views%2Fusers.view.lkml?line=27',
        permanent: null,
        source_file: 'views/users.view.lkml',
        source_file_path: 'thelook/views/users.view.lkml',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        can_filter: false,
        category: Category.dimension,
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: 'Created Date',
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: true,
        is_filter: false,
        is_numeric: false,
        label: 'Users Created Raw',
        label_from_parameter: null,
        label_short: 'Created Raw',
        name: 'users.created_raw',
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'date_raw',
        view: 'users',
        view_label: 'Users',
        dynamic: false,
        original_view: 'users',
        dimension_group: 'users.created',
        error: null,
        field_group_variant: 'Raw',
        measure: false,
        parameter: false,
        primary_key: false,
        project_name: 'thelook',
        scope: 'users',
        suggest_dimension: 'users.created_raw',
        suggest_explore: 'orders',
        suggestable: false,
        is_fiscal: false,
        is_timeframe: false,
        can_time_filter: false,
        lookml_link: '/projects/thelook/files/views%2Fusers.view.lkml?line=27',
        permanent: null,
        source_file: 'views/users.view.lkml',
        source_file_path: 'thelook/views/users.view.lkml',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        can_filter: true,
        category: Category.dimension,
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: 'Created Date',
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: false,
        label: 'Users Created Time',
        label_from_parameter: null,
        label_short: 'Created Time',
        name: 'users.created_time',
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'date_time',
        view: 'users',
        view_label: 'Users',
        dynamic: false,
        original_view: 'users',
        dimension_group: 'users.created',
        error: null,
        field_group_variant: 'Time',
        measure: false,
        parameter: false,
        primary_key: false,
        project_name: 'thelook',
        scope: 'users',
        suggest_dimension: 'users.created_time',
        suggest_explore: 'orders',
        suggestable: false,
        is_fiscal: false,
        is_timeframe: true,
        can_time_filter: true,
        lookml_link: '/projects/thelook/files/views%2Fusers.view.lkml?line=27',
        permanent: null,
        source_file: 'views/users.view.lkml',
        source_file_path: 'thelook/views/users.view.lkml',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        can_filter: true,
        category: Category.dimension,
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: 'Created Date',
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: false,
        label: 'Users Created Week',
        label_from_parameter: null,
        label_short: 'Created Week',
        name: 'users.created_week',
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'date_week',
        view: 'users',
        view_label: 'Users',
        dynamic: false,
        original_view: 'users',
        dimension_group: 'users.created',
        error: null,
        field_group_variant: 'Week',
        measure: false,
        parameter: false,
        primary_key: false,
        project_name: 'thelook',
        scope: 'users',
        suggest_dimension: 'users.created_week',
        suggest_explore: 'orders',
        suggestable: false,
        is_fiscal: false,
        is_timeframe: true,
        can_time_filter: false,
        lookml_link: '/projects/thelook/files/views%2Fusers.view.lkml?line=27',
        permanent: null,
        source_file: 'views/users.view.lkml',
        source_file_path: 'thelook/views/users.view.lkml',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        can_filter: true,
        category: Category.dimension,
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: 'Created Date',
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: false,
        label: 'Users Created Year',
        label_from_parameter: null,
        label_short: 'Created Year',
        name: 'users.created_year',
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'date_year',
        view: 'users',
        view_label: 'Users',
        dynamic: false,
        original_view: 'users',
        dimension_group: 'users.created',
        error: null,
        field_group_variant: 'Year',
        measure: false,
        parameter: false,
        primary_key: false,
        project_name: 'thelook',
        scope: 'users',
        suggest_dimension: 'users.created_year',
        suggest_explore: 'orders',
        suggestable: false,
        is_fiscal: false,
        is_timeframe: true,
        can_time_filter: false,
        lookml_link: '/projects/thelook/files/views%2Fusers.view.lkml?line=27',
        permanent: null,
        source_file: 'views/users.view.lkml',
        source_file_path: 'thelook/views/users.view.lkml',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        can_filter: true,
        category: Category.dimension,
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: null,
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: false,
        label: 'Users Email',
        label_from_parameter: null,
        label_short: 'Email',
        name: 'users.email',
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'string',
        view: 'users',
        view_label: 'Users',
        dynamic: false,
        original_view: 'users',
        dimension_group: null,
        error: null,
        field_group_variant: 'Email',
        measure: false,
        parameter: false,
        primary_key: false,
        project_name: 'thelook',
        scope: 'users',
        suggest_dimension: 'users.email',
        suggest_explore: 'orders',
        suggestable: true,
        is_fiscal: false,
        is_timeframe: false,
        can_time_filter: false,
        lookml_link: '/projects/thelook/files/views%2Fusers.view.lkml?line=41',
        permanent: null,
        source_file: 'views/users.view.lkml',
        source_file_path: 'thelook/views/users.view.lkml',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        can_filter: true,
        category: Category.dimension,
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: null,
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: false,
        label: 'Users First Name',
        label_from_parameter: null,
        label_short: 'First Name',
        name: 'users.first_name',
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'string',
        view: 'users',
        view_label: 'Users',
        dynamic: false,
        original_view: 'users',
        dimension_group: null,
        error: null,
        field_group_variant: 'First Name',
        measure: false,
        parameter: false,
        primary_key: false,
        project_name: 'thelook',
        scope: 'users',
        suggest_dimension: 'users.first_name',
        suggest_explore: 'orders',
        suggestable: true,
        is_fiscal: false,
        is_timeframe: false,
        can_time_filter: false,
        lookml_link: '/projects/thelook/files/views%2Fusers.view.lkml?line=46',
        permanent: null,
        source_file: 'views/users.view.lkml',
        source_file_path: 'thelook/views/users.view.lkml',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        can_filter: true,
        category: Category.dimension,
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: null,
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: false,
        label: 'Users Gender',
        label_from_parameter: null,
        label_short: 'Gender',
        name: 'users.gender',
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'string',
        view: 'users',
        view_label: 'Users',
        dynamic: false,
        original_view: 'users',
        dimension_group: null,
        error: null,
        field_group_variant: 'Gender',
        measure: false,
        parameter: false,
        primary_key: false,
        project_name: 'thelook',
        scope: 'users',
        suggest_dimension: 'users.gender',
        suggest_explore: 'orders',
        suggestable: true,
        is_fiscal: false,
        is_timeframe: false,
        can_time_filter: false,
        lookml_link: '/projects/thelook/files/views%2Fusers.view.lkml?line=51',
        permanent: null,
        source_file: 'views/users.view.lkml',
        source_file_path: 'thelook/views/users.view.lkml',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        can_filter: true,
        category: Category.dimension,
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: null,
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: true,
        label: 'Users ID',
        label_from_parameter: null,
        label_short: 'ID',
        name: 'users.id',
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'number',
        view: 'users',
        view_label: 'Users',
        dynamic: false,
        original_view: 'users',
        dimension_group: null,
        error: null,
        field_group_variant: 'ID',
        measure: false,
        parameter: false,
        primary_key: true,
        project_name: 'thelook',
        scope: 'users',
        suggest_dimension: 'users.id',
        suggest_explore: 'orders',
        suggestable: false,
        is_fiscal: false,
        is_timeframe: false,
        can_time_filter: false,
        lookml_link: '/projects/thelook/files/views%2Fusers.view.lkml?line=5',
        permanent: null,
        source_file: 'views/users.view.lkml',
        source_file_path: 'thelook/views/users.view.lkml',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        can_filter: true,
        category: Category.dimension,
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: null,
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: false,
        label: 'Users Last Name',
        label_from_parameter: null,
        label_short: 'Last Name',
        name: 'users.last_name',
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'string',
        view: 'users',
        view_label: 'Users',
        dynamic: false,
        original_view: 'users',
        dimension_group: null,
        error: null,
        field_group_variant: 'Last Name',
        measure: false,
        parameter: false,
        primary_key: false,
        project_name: 'thelook',
        scope: 'users',
        suggest_dimension: 'users.last_name',
        suggest_explore: 'orders',
        suggestable: true,
        is_fiscal: false,
        is_timeframe: false,
        can_time_filter: false,
        lookml_link: '/projects/thelook/files/views%2Fusers.view.lkml?line=56',
        permanent: null,
        source_file: 'views/users.view.lkml',
        source_file_path: 'thelook/views/users.view.lkml',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        can_filter: true,
        category: Category.dimension,
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: null,
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: false,
        label: 'Users State',
        label_from_parameter: null,
        label_short: 'State',
        name: 'users.state',
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'string',
        view: 'users',
        view_label: 'Users',
        dynamic: false,
        original_view: 'users',
        dimension_group: null,
        error: null,
        field_group_variant: 'State',
        measure: false,
        parameter: false,
        primary_key: false,
        project_name: 'thelook',
        scope: 'users',
        suggest_dimension: 'users.state',
        suggest_explore: 'orders',
        suggestable: true,
        is_fiscal: false,
        is_timeframe: false,
        can_time_filter: false,
        lookml_link: '/projects/thelook/files/views%2Fusers.view.lkml?line=61',
        permanent: null,
        source_file: 'views/users.view.lkml',
        source_file_path: 'thelook/views/users.view.lkml',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        can_filter: true,
        category: Category.dimension,
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: null,
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: false,
        label: 'Users Zip',
        label_from_parameter: null,
        label_short: 'Zip',
        map_layer: {
          url: 'https://maps-tiles-a.lookercdn.com/us_zcta510/{z}/{x}/{y}.pbf',
          name: 'us_zipcode_tabulation_areas',
          feature_key: 'tl_2016_us_zcta510geojson',
          property_key: 'ZCTA5CE10',
          property_label_key: null,
          projection: null,
          extents_json_url:
            'https://maps-tiles-b.lookercdn.com/us_zcta510/extents.json',
          max_zoom_level: 12,
          min_zoom_level: null,
        },
        name: 'users.zip',
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'zipcode',
        view: 'users',
        view_label: 'Users',
        dynamic: false,
        original_view: 'users',
        dimension_group: null,
        error: null,
        field_group_variant: 'Zip',
        measure: false,
        parameter: false,
        primary_key: false,
        project_name: 'thelook',
        scope: 'users',
        suggest_dimension: 'users.zip',
        suggest_explore: 'orders',
        suggestable: true,
        is_fiscal: false,
        is_timeframe: false,
        can_time_filter: false,
        lookml_link: '/projects/thelook/files/views%2Fusers.view.lkml?line=66',
        permanent: null,
        source_file: 'views/users.view.lkml',
        source_file_path: 'thelook/views/users.view.lkml',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
    ],
    measures: [
      {
        can_filter: true,
        category: Category.measure,
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: null,
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: true,
        label: 'Orders Count',
        label_from_parameter: null,
        label_short: 'Count',
        name: 'orders.count',
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'count',
        view: 'orders',
        view_label: 'Orders',
        dynamic: false,
        original_view: 'orders',
        dimension_group: null,
        error: null,
        field_group_variant: 'Count',
        measure: true,
        parameter: false,
        primary_key: false,
        project_name: 'thelook',
        scope: 'orders',
        suggest_dimension: 'orders.count',
        suggest_explore: 'orders',
        suggestable: false,
        is_fiscal: false,
        is_timeframe: false,
        can_time_filter: false,
        lookml_link: '/projects/thelook/files/views%2Forders.view.lkml?line=36',
        permanent: null,
        source_file: 'views/orders.view.lkml',
        source_file_path: 'thelook/views/orders.view.lkml',
        sql: null,
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        can_filter: true,
        category: Category.measure,
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: null,
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: true,
        label: 'Users Count',
        label_from_parameter: null,
        label_short: 'Count',
        name: 'users.count',
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'count_distinct',
        view: 'users',
        view_label: 'Users',
        dynamic: false,
        original_view: 'users',
        dimension_group: null,
        error: null,
        field_group_variant: 'Count',
        measure: true,
        parameter: false,
        primary_key: false,
        project_name: 'thelook',
        scope: 'users',
        suggest_dimension: 'users.count',
        suggest_explore: 'orders',
        suggestable: false,
        is_fiscal: false,
        is_timeframe: false,
        can_time_filter: false,
        lookml_link: '/projects/thelook/files/views%2Fusers.view.lkml?line=71',
        permanent: null,
        source_file: 'views/users.view.lkml',
        source_file_path: 'thelook/views/users.view.lkml',
        sql: null,
        sql_case: null,
        filters: null,
        times_used: 0,
      },
    ],
    parameters: [],
    filters: [],
  },
  aliases: null,
  always_filter: null,
  always_join: [],
  access_filters: [],
  index_fields: [],
  model_name: 'thelook',
  tags: [],
  group_label: 'Thelook',
  scopes: ['orders', 'users'],
  can_total: true,
  can_see_lookml: true,
  can_develop: true,
  can_save: true,
  can_explain: true,
  can_pivot_in_db: true,
  can_subtotal: true,
  has_timezone_support: true,
  supports_cost_estimate: true,
  connection_name: 'thelook',
  null_sort_treatment: 'low',
  source_file: 'thelook/models/thelook.model.lkml',
  view_name: 'orders',
  hidden: false,
};

export function Basic({
  label = 'Filter by',
  tree = createExploreViewsTree(exploreData),
  onSelectedFieldChange,
  ...props
}: TreeSelectProps) {
  const [field, setField] = useState();
  const [section, setSection] = useState();
  const handleChange = (fieldData: any) => {
    setField(fieldData.field);
    setSection(fieldData.fieldOptions.view_label);
    onSelectedFieldChange?.(fieldData);
  };
  return (
    <ExtendComponentsThemeProvider
      themeCustomizations={{ defaults: { externalLabel: false } }}
    >
      <Box width={400} p="u3">
        <TreeSelect
          label={label}
          onSelectedFieldChange={handleChange}
          tree={tree}
          {...props}
          selectedSection={section}
          selectedField={field}
        />
      </Box>
    </ExtendComponentsThemeProvider>
  );
}

export function ShortcutTree({
  tree = createExploreViewsTree(exploreData),
  shortcutTree = mockShortcutTree,
  onSelectedFieldChange,
  ...props
}: TreeSelectProps) {
  const [field, setField] = useState();
  const [section, setSection] = useState();
  const handleChange = (fieldData: any) => {
    setField(fieldData.field);
    setSection(fieldData.fieldOptions.view_label);
    onSelectedFieldChange?.(fieldData);
  };
  // padding-top 300 is to test fix for b/286167535
  // where expanding a node should not overflow the page
  return (
    <Box width={400} p="u3" pt={300}>
      <TreeSelect
        onSelectedFieldChange={handleChange}
        tree={tree}
        shortcutTree={shortcutTree}
        selectedSection={section}
        selectedField={field}
        {...props}
      />
    </Box>
  );
}

const getRandomInteger = (limit: number) => Math.floor(Math.random() * limit);

const preamble = `We the People of the United States, in Order to form a more perfect Union,
establish Justice, insure domestic Tranquility, provide for the common
defense, promote the general Welfare, and secure the Blessings of Liberty
to ourselves and our Posterity, do ordain and establish this Constitution
for the United States of America.`;

const getString = (lengthLimit = 30): string => {
  const startLimit = preamble.length - 50;
  const length = getRandomInteger(lengthLimit) || 1;
  const startIndex = getRandomInteger(startLimit);
  const substring = preamble.substr(startIndex, length).trim();
  return substring || getString(lengthLimit);
};

const getItems = (
  prefix: string,
  labelLength: number,
  canNest = false
): TreeModel[] => {
  return Array.from(Array(10), (_, i) => {
    if (canNest && i % 3 === 2) {
      const labelText = labelLength ? `: ${getString(labelLength)}` : '';
      const value = `${prefix}-${i} ${labelText}`;
      return {
        label: value,
        children: getItems(`${prefix}-${i}`, labelLength),
        value,
        id: value,
      };
    }
    const itemText = labelLength ? `${getString(labelLength)}` : '';
    const field = `${prefix}-${i} ${itemText}`;
    return {
      label: itemText,
      payload: {
        field,
        fieldOptions: { view_label: `${prefix}-${i}` },
      },
      value: itemText,
      id: field,
    };
  });
};

const getTrees = (labelLength: number): TreeModel[] =>
  Array.from(Array(100), (_, i) => {
    const labelText = labelLength ? `: ${getString(labelLength)}` : '';
    const value = `${i} ${labelText}`;
    return {
      value,
      children: getItems(String(i), labelLength, true),
      id: value,
    };
  });

export function Windowing({
  tree = getTrees(30),
  shortcutTree = mockShortcutTree,
  onSelectedFieldChange,
  ...props
}: TreeSelectProps) {
  const [field, setField] = useState();
  const [section, setSection] = useState();
  const handleChange = (fieldData: any) => {
    setField(fieldData.field);
    setSection(fieldData.fieldOptions.view_label);
    onSelectedFieldChange?.(fieldData);
  };

  return (
    <Box width={400} p="u3">
      <TreeSelect
        onSelectedFieldChange={handleChange}
        tree={tree}
        shortcutTree={shortcutTree}
        {...props}
        selectedSection={section}
        selectedField={field}
      />
    </Box>
  );
}

export function WithoutDropdown({
  label = 'Filter by',
  tree = createExploreViewsTree(exploreData),
  withDropdown = false,
  onSelectedFieldChange,
  ...props
}: TreeSelectProps) {
  const handleChange = (fieldData: any) => {
    onSelectedFieldChange?.(fieldData);
  };
  return (
    <TreeSelect
      label={label}
      treeHeight={200}
      onSelectedFieldChange={handleChange}
      tree={tree}
      withDropdown={withDropdown}
      {...props}
    >
      <Box mb="xsmall">
        <FieldToggleSwitch label="Advanced" />
      </Box>
    </TreeSelect>
  );
}
