version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "13:00"
  open-pull-requests-limit: 99
  reviewers:
  - lukelooker
  versioning-strategy: increase
