export const lensText: string
export const isDisplay1: string
export const isDisplay2: string
export const isDisplay3: string
export const isHeading1: string
export const isHeading2: string
export const isHeading3: string
export const isHeading4: string
export const isHeading5: string
export const isHeading6: string
export const fontWeightLight: string
export const fontWeightNormal: string
export const fontWeightSemiBold: string
export const fontWeightBold: string
export const fontWeightExtraBold: string
export const transformUpper: string
export const transformLower: string
export const transformCaps: string
export const transformNone: string
export const alignLeft: string
export const alignRight: string
export const alignCenter: string
export const alignJustify: string
export const isSecondary: string
export const isSubdued: string
export const isPositive: string
export const isCritical: string
export const isTruncated: string
export const isCode: string
