import type { FilterDateTimeModel, FilterModel } from '../../types';
export declare const sanitizeDate: (item: FilterModel) => {
    id: string;
    is: boolean;
    type: "past";
    unit: any;
    value: any;
    year?: undefined;
    month?: undefined;
    range?: undefined;
    date?: undefined;
    startInterval?: undefined;
    endInterval?: undefined;
    intervalType?: undefined;
} | {
    id: string;
    is: boolean;
    type: "this" | "next" | "last";
    unit: any;
    value?: undefined;
    year?: undefined;
    month?: undefined;
    range?: undefined;
    date?: undefined;
    startInterval?: undefined;
    endInterval?: undefined;
    intervalType?: undefined;
} | {
    id: string;
    is: boolean;
    type: "year";
    year: any;
    unit?: undefined;
    value?: undefined;
    month?: undefined;
    range?: undefined;
    date?: undefined;
    startInterval?: undefined;
    endInterval?: undefined;
    intervalType?: undefined;
} | {
    id: string;
    is: boolean;
    type: "month";
    year: any;
    month: any;
    unit?: undefined;
    value?: undefined;
    range?: undefined;
    date?: undefined;
    startInterval?: undefined;
    endInterval?: undefined;
    intervalType?: undefined;
} | {
    id: string;
    is: boolean;
    type: "before" | "after";
    range: any;
    unit: any;
    value: any;
    date: FilterDateTimeModel;
    year?: undefined;
    month?: undefined;
    startInterval?: undefined;
    endInterval?: undefined;
    intervalType?: undefined;
} | {
    id: string;
    is: boolean;
    type: "thisRange";
    startInterval: any;
    endInterval: any;
    unit?: undefined;
    value?: undefined;
    year?: undefined;
    month?: undefined;
    range?: undefined;
    date?: undefined;
    intervalType?: undefined;
} | {
    id: string;
    is: boolean;
    type: "on";
    date: {
        year: number;
        month: number;
        day: number;
    };
    unit?: undefined;
    value?: undefined;
    year?: undefined;
    month?: undefined;
    range?: undefined;
    startInterval?: undefined;
    endInterval?: undefined;
    intervalType?: undefined;
} | {
    id: string;
    is: boolean;
    type: "relative";
    startInterval: any;
    endInterval: any;
    intervalType: any;
    unit?: undefined;
    value?: undefined;
    year?: undefined;
    month?: undefined;
    range?: undefined;
    date?: undefined;
} | {
    type: string;
    id: string;
    is: boolean;
    date?: FilterDateTimeModel | undefined;
    start?: FilterDateTimeModel | undefined;
    end?: FilterDateTimeModel | undefined;
    unit?: undefined;
    value?: undefined;
    year?: undefined;
    month?: undefined;
    range?: undefined;
    startInterval?: undefined;
    endInterval?: undefined;
    intervalType?: undefined;
};
