import type { AllPresetTimeframes } from '../../../types/relative_timeframe_types';
export declare const useRelativeTimeframePresets: () => {
    Today: string;
    Yesterday: string;
    "Last 7 Days": string;
    "Last 14 Days": string;
    "Last 28 Days": string;
    "Last 30 Days": string;
    "Last 90 Days": string;
    "Last 180 Days": string;
    "Last 365 Days": string;
    "Year To Date": string;
    "This Week": string;
    "This Month": string;
    "This Quarter": string;
    "This Year": string;
    "Previous Week": string;
    "Previous Month": string;
    "Previous Quarter": string;
    "Previous Year": string;
};
