export const button: string;
export const sizeExtraSmall: string;
export const sizeSmall: string;
export const sizeLarge: string;
export const foo: string;
export const modeLight: string;
export const modeGhost: string;
export const modeScary: string;
export const modeDisabled: string;
