export declare const shouldForwardProp: genericShouldForwardProp;
export * from './color';
export * from './elevation';
export type { LegacySpaceRamp, SpaceRamp, SpacingSizes, SpaceProps, UnitRamp, UnitSizes, } from './space';
export { units } from './space';
export * from './theme';
export * from './system';
export { transitions } from './tokens/transitions';
export * from './tokens/breakpoints';
export * from './utils';
