m = angular.module "lens.atoms", [
  "lens.atoms.block_grid"
  "lens.atoms.borders"
  "lens.atoms.colors"
  "lens.atoms.effects"
  "lens.atoms.flexbox"
  "lens.atoms.grid"
  "lens.atoms.icons"
  "lens.atoms.layout"
  "lens.atoms.spacing_sizing"
  "lens.atoms.typography"
]

require "./block_grid"
require "./borders"
require "./colors"
require "./effects"
require "./flexbox"
require "./grid"
require "./icons"
require "./layout"
require "./spacing_sizing"
require "./typography"
