m = angular.module "lens.atoms", [
  "lens.atoms.block_grid"
  "lens.atoms.borders"
  "lens.atoms.colors"
  "lens.atoms.effects"
  "lens.atoms.flexbox"
  "lens.atoms.grid"
  "lens.atoms.icons"
  "lens.atoms.layout"
  "lens.atoms.spacing_sizing"
  "lens.atoms.typography"
]

require "./block_grid.coffee"
require "./borders.coffee"
require "./colors.coffee"
require "./effects.coffee"
require "./flexbox.coffee"
require "./grid.coffee"
require "./icons.coffee"
require "./layout.coffee"
require "./spacing_sizing.coffee"
require "./typography.coffee"
