m = angular.module "lens.atoms", [
  "lens.atoms.block_grid"
  "lens.atoms.borders"
  "lens.atoms.buttons"
  "lens.atoms.colors"
  "lens.atoms.flexbox"
  "lens.atoms.forms"
  "lens.atoms.grid"
  "lens.atoms.icons"
  "lens.atoms.layout"
  "lens.atoms.responsive"
  "lens.atoms.tables"
  "lens.atoms.typography"
]

require "./block_grid.coffee"
require "./borders.coffee"
require "./buttons.coffee"
require "./colors.coffee"
require "./flexbox.coffee"
require "./forms.coffee"
require "./grid.coffee"
require "./icons.coffee"
require "./layout.coffee"
require "./responsive.coffee"
require "./tables.coffee"
require "./typography.coffee"
