import type { BlendColors } from './blends';
import type { StatefulColors } from './stateful';
import type { SpecifiableColors, TextColor } from './specifiable';
import type { DerivativeColors } from './derivative';
export declare type Colors = SpecifiableColors & DerivativeColors & BlendColors & StatefulColors;
export declare type TextColors = TextColor;
export { coreColors, intentColors, specifiableColors } from './specifiable';
export type { DerivativeColors } from './derivative';
export type { CoreColors, IllustrationColors, IntentColors, SpecifiableColors, SpecifiableTextColors, } from './specifiable';
export type { BlendColors } from './blends';
export type { ExtendedStatefulColor, StatefulColor, StatefulColors, StatefulColorChoices, } from './stateful';
export type { ColorProps } from 'styled-system';
export type { TextColorProps } from './textColor';
export { backgroundColor } from './backgroundColor';
export { uiColors, textColors } from './blends';
export { derivativeColors } from './derivative';
export { textColor } from './textColor';
export { specifiableTextColors } from './specifiable';
