on: [push]
name: "Test suite (Jest)"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install &> /dev/null
      - run: yarn lint
    env:
      CI: true
